### ISSUE TITLE
访问不了

### ISSUE THREAD

**Issue by KAIXIE** [react-translate-team/react-router-CN#31]
访问不了，太垃圾了吧，要做就做好

**Comment by simple7** [comment]
就是

**Comment by justjavac** [comment]
稍等，正在迁移。源主机被 ddos 攻击了，而且原维护者肉身翻墙了 😂

**Comment by NineLeo** [comment]
支持作者, 加油

**Comment by lznism** [comment]
@justjavac 还没有迁移完吗？现在还访问不了

**Comment by songxx0209** [comment]
还是访问不了

**Comment by songxx0209** [comment]
还是访问不了

**Comment by nelhu** [comment]
遇到问题了吗 好多开发者等着呢 我们怎么帮你啊

**Comment by leidenglai** [comment]
> 访问不了，太垃圾了吧，要做就做好

可以clone 到本地，然后安装运行，访问http://127.0.0.1:8080就可以了

**Comment by ghostchan** [comment]
我在阿里云放了一份，大家可以试试  http://router.happyfe.com

**Comment by Lizhooh** [comment]
@KAIXIE 你行你来，别这里伸手党的语气。

**Comment by BengBu-YueZhang** [comment]
@KAIXIE 你这个纱布，作者没有义务
